### ISSUE TITLE
SyntaxError: Unexpected token } in JSON at position 106

### ISSUE THREAD

**Issue by darksterix** [Tudmotu/solarizd#32]
i keep on getting this error, i've been trying to fix it, and it causes more error, when i try deleting the }

**Comment by darksterix** [comment]
this is the complete error when i inspect it

`app.browser.js:17122 SyntaxError: Unexpected token } in JSON at position 106
    at Object.parse (native)
    at fromJson (http://localhost:8080/template/solar/solarizd/target/app.browser.js:11788:55)
    at defaultHttpResponseTransform (http://localhost:8080/template/solar/solarizd/target/app.browser.js:15504:208)
    at http://localhost:8080/template/solar/solarizd/target/app.browser.js:15530:137
    at forEach (http://localhost:8080/template/solar/solarizd/target/app.browser.js:11396:329)
    at transformData (http://localhost:8080/template/solar/solarizd/target/app.browser.js:15530:105)
    at transformResponse (http://localhost:8080/template/solar/solarizd/target/app.browser.js:16153:42)
    at processQueue (http://localhost:8080/template/solar/solarizd/target/app.browser.js:17474:354)
    at http://localhost:8080/template/solar/solarizd/target/app.browser.js:17474:658
    at Scope.$eval (http://localhost:8080/template/solar/solarizd/target/app.browser.js:18057:63)`

**Comment by Tudmotu** [comment]
Hard to say what's the issue from this info.
Did you add an apikeys.json file?
https://github.com/Tudmotu/solarizd#api-keys
It should at least contain a youtube api key.

Also, if you'll use ``grunt connect:src`` to run your server, the place where the error comes from will be a bit more clear.

**Comment by darksterix** [comment]
it didn't work until i moved the files in src file to the root, `localhost:8080`, the error i got was after i tried modifying the app.browser.js to fit the file path, from `/html/..` to `/template/solar/target/src/html/'` , and that didn't work. so i just moved the files in src to the base and it worked again.
